[package]
name = "SpoolEase"
homepage = "SpoolEase.io"
version = "0.5.0-b.66"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.84"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
opt-level = 's'
lto = 'fat'
overflow-checks = false

[profile.release.package.esp-wifi]
opt-level = 3

[profile.dev]
lto = false

[profile.dev.package.esp-wifi]
opt-level = 3

[patch.crates-io]
bitvec = { git = "https://github.com/arctic-alpaca/ferrilab" }
radium = { git = "https://github.com/arctic-alpaca/ferrilab" }

edge-nal-embassy = { git = "https://github.com/yanshay/edge-net" }
edge-http = { git = "https://github.com/yanshay/edge-net" } 
edge-dhcp = { git = "https://github.com/yanshay/edge-net" } 
edge-nal = { git = "https://github.com/yanshay/edge-net" } 
edge-captive = { git = "https://github.com/yanshay/edge-net" } 
edge-ws = { git = "https://github.com/yanshay/edge-net" } 

[build-dependencies]
slint-build = "1.9.1"
walkdir = "2.5.0"

[dependencies]
#TODO: Important - lock to specific tag when released
framework = { package = "esp-hal-app-framework", git = "https://github.com/yanshay/esp-hal-app/", tag = "0.5.1", features = ["esp32s3", "improv-jtag-serial", "wt32-sc01-plus"] }
framework_macros = { package = "esp-hal-app-framework-macros", git = "https://github.com/yanshay/esp-hal-app/", tag = "0.5.1" }
# framework = { package = "esp-hal-app-framework", path = "../../../esp-hal-app/esp-hal-app-framework/", features = ["esp32s3", "improv-jtag-serial", "wt32-sc01-plus"] }
# framework_macros = { package = "esp-hal-app-framework-macros", path = "../../../esp-hal-app/esp-hal-app-framework-macros/" }
esp32s3 = { version = "0.30.0" }

# Esp-Hal Crates
xtensa-lx-rt = { version = "0.18.0", features = ["float-save-restore"] }
esp-hal = { version = "0.23.1", features = ["quad-psram"] }
esp-backtrace = { version = "0.15.0", features = [ "panic-handler", "println", "exception-handler"] }
esp-println = { version = "0.13.0", default-features = false, features = ["critical-section", "colors", "auto", "log"] }
esp-hal-embassy = { version = "0.6.0" }
esp-partition-table = { version = "0.1.2" }
esp-wifi = { version = "0.12.0", features = [ "wifi", "utils", "esp-alloc"] }
# esp-mbedtls = { git = "https://github.com/esp-rs/esp-mbedtls.git", features = [ "async" ], rev = "1806f8f622b08a9b54de91814eea13c6b3d9ff1c" }
esp-mbedtls = { git = "https://github.com/yanshay/esp-mbedtls.git", features = [ "async", "esp32s3" ], branch = "yanshay_reuse_session_esp-hal-0.23.1" }
esp-alloc = { version = "0.6.0" } # features = ["internal-heap-stats"] }
esp-storage = { version = "0.4.0", features = [ "nor-flash" ] }

esp-hal-ota = { version = "0.3.2" }

# Embedded crates
embedded-hal = { version = "1.0.0" }
embedded-hal-async = { version = "1.0.0" }
embedded-hal-bus = { version = "0.2.0", features = ["async"] }
embedded-storage = { version = "0.3.1" }
embedded-storage-async = { version = "0.4.1" }
embedded-io = "0.6.1"
embedded-io-async = { version = "0.6.1" }

# Embassy & Async crates
embassy-embedded-hal = { version = "0.3.0" }
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
embassy-executor = { version = "0.7.0", features = ["nightly"] }
embassy-net = { version = "0.6.0", features = ["raw", "tcp", "udp", "dhcpv4", "medium-ethernet", "multicast" ] }
embassy-futures = { version = "0.1.1" }
embassy-sync = { version = "0.6.2" }
futures = { version = "0.3.31", features = ["alloc"], default-features = false }
futures-util = { version = "0.3.31", default-features = false }

# Storage crates
sequential-storage = { git = "https://github.com/tweedegolf/sequential-storage", features = [ "alloc", ], rev = "b6f7da77b7f3d66bc1ac36992a6a7b399b5ba030" }

# Display & Touch crates
display-interface = { version = "0.5.0" }
display-interface-parallel-gpio = { version = "0.7.0" }
mipidsi = { version = "0.8.0" }
slint = { version = "1.9.2", default-features = false, features = [ "libm", "unsafe-single-threaded", "compat-1-2", "renderer-software" ] }
ft6x36 = { version = "0.6.1" }

# Networking crates
smoltcp = { version = "0.12.0", default-features = false, features = [ "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }

# edge-nal-embassy = "0.5.0"
# edge-dhcp = "0.5.0"
# edge-nal = "0.5.0"
# edge-captive = "0.5.0"
# edge-http = "0.5.1"
# edge-ws = "0.4.0"

# edge-nal-embassy = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-nal-embassy/" }
# edge-http = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-http/" }
# edge-dhcp = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-dhcp/" }
# edge-nal = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-nal/" }
# edge-captive = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-captive/" }
# edge-ws = { path = "../../../../../OpenSourceProj/forked/edge-net/edge-ws/" }

edge-nal-embassy = { git = "https://github.com/yanshay/edge-net" }
edge-http = { git = "https://github.com/yanshay/edge-net" } 
edge-dhcp = { git = "https://github.com/yanshay/edge-net" } 
edge-nal = { git = "https://github.com/yanshay/edge-net" } 
edge-captive = { git = "https://github.com/yanshay/edge-net" } 
edge-ws = { git = "https://github.com/yanshay/edge-net" } 

# picoserve = {version = "0.14.1", git = "https://github.com/sammhicks/picoserve", rev = "5d40ea410efa4c2e313cfaa19f62f844ece1fd55", features = ["alloc", "embassy"] }
picoserve = {version = "0.15.1", features = ["alloc", "embassy"] }


# Utility crates
cfg-if = "1.0.0"
no_std_io = { version = "0.6.0", default-features = false, features = [ "alloc" ] }
log = { version = "0.4.22", features = ["serde"] }
heapless = "0.8.0"
critical-section = "1.2.0"
static_cell = { version = "2.1", features = ["nightly"] }
once_cell = { version = "1.20.2", default-features = false, features = ["alloc"] }
deku = { version = "0.17.0", default-features = false, features = ["alloc"] }
anyhow = { version = "1.0.91", default-features = false }
snafu = { git = "https://github.com/shepmaster/snafu", rev = "aedc9db8c04a437b4c547efd4d73e9337fa43a4a", default-features = false, features = ["rust_1_81", "alloc"]} # , "backtraces-impl-backtrace-crate"]} 
hashbrown = { version = "0.15.0", features = ["serde"] }
serde = { version = "1.0.213", default-features = false, features = [ "derive", "alloc", ] }
serde_json = { version = "1.0.132", default-features = false, features = [ "alloc", ] }
serde-csv-core = "0.3.2"
serde_with = { version = "3.16.0", default-features = false, features = ["alloc", "macros", "base64", "hashbrown_0_15", "hex"]}
pasetors = { version = "0.7.0", default-features = false, features = ["v4"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
getrandom = { version = "0.2.15", features = ["custom"] }
semver = { version = "1.0.25", default-features = false }
derivative = { version = "2.2.0", features = ["use_core"] }
siphasher = { version = "1.0.1", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
fnv = { version = "1.0.7", default-features = false }
hex = {version = "0.4.3", default-features = false, features = ["alloc"]}
embedded-sdmmc = { git = "https://github.com/yanshay/embedded-sdmmc-rs", branch = "yanshay_bisync" }
# url = { version ="2.5.7", default-features = false }
percent-encoding = {version = "2.3.2", default-features = false, features = ["alloc"]}

# Security/Crypto crates
aes-gcm = { version = "0.10" }  # AES-GCM encryption/decryption
# getrandom = { version = "0.3.0", default-features = false }
rand = { version = "0.8", default-features = false }
aes="0.8.4"
ctr = "0.9.2"
pbkdf2 = { version = "0.12", features = ["simple"] }
sha2 = { version = "0.10.8", default-features = false}
hmac = { version = "0.12.1", default-features = false}

# Application specific crates
mqttrust = { version = "0.6.0" }
pn532 = { git = "https://github.com/yanshay/pn532", branch ="yanshay_async_full", default-features = false }
# pn532 = { path="../../../../../OpenSourceProj/forked/pn532/", default-features = false }
regex = { version = "1.11.1", default-features = false }
shared = { path = "../shared/" }
# ndef-rs = { path = "../../../../../../OpenSourceProj/forked/ndef-rs/ndef", default-features = false}
ndef-rs = { git = "https://github.com/yanshay/ndef-rs" , branch = "yanshay_no_std", default-features = false}
minicbor = { version = "0.26.5", default-features =false, features = ["alloc", "derive", "half"]}
minicbor-derive = {version = "0.16.2" }

[features]
default = ["esp32s3"]

esp32s3 = [
  "esp-hal/esp32s3",
  "esp-backtrace/esp32s3",
  "esp-println/esp32s3",
  "esp-wifi/esp32s3",
  "esp-mbedtls/esp32s3",
  "esp-hal-embassy/esp32s3",
  "esp-storage/esp32s3",
  "esp-hal-ota/esp32s3"
]

esp32 = [
  "esp-hal/esp32",
  "esp-backtrace/esp32",
  "esp-println/esp32",
  "esp-wifi/esp32",
  "esp-mbedtls/esp32",
]
esp32c3 = [
  "esp-hal/esp32c3",
  "esp-backtrace/esp32c3",
  "esp-println/esp32c3",
  "esp-wifi/esp32c3",
  "esp-mbedtls/esp32c3",
]
esp32s2 = [
  "esp-hal/esp32s2",
  "esp-backtrace/esp32s2",
  "esp-println/esp32s2",
  "esp-wifi/esp32s2",
  "esp-mbedtls/esp32s2",
]
